### ISSUE TITLE
As a traveler I want to see pictures of the places So that I can decide which I prefer 

### ISSUE THREAD

**Issue by eleniGr** [aposgial/Project_E3#5]
Ο χρήστης να μπορεί  να αποθηκεύει τις τοποθεσίες που θέλει να επισκεφτεί

**Comment by Stefkostas** [comment]
Ως ταξιδιώτης θέλω να δω φωτογραφίες από τα μέρη για να αποφασίσω ποιο προτιμώ να επισκεφτώ.
